### ISSUE TITLE
E3.1 

### ISSUE THREAD

**Issue by ferruirob** [gii-is-psg2/PSG2-1920-G6-62#61]
As a group, extend the technical reports created as a result of A3.3 and A3.4 to also analyze the differences among the results of the metrics and the analysis in L2 and L3. The document should also include a discussion about the causes of such differences.

A3.3 -> Yoana
A3.4 -> Juan Pablo

**Comment by yoadimpen** [comment]
E3.1 en relación al A3.3 está completo.
